################################################################################
# This file contains the configuration for the cortex-annotate toolkit. By
# editing this file, one can configure cortex-annotate to work with various
# datasets and to enable annotation of specific contours, points, and
# boundaries.

display:
  figsize: [4, 4]
  dpi: 128
  active_style:
    color: [0.97, 0.97, 0.97]
    markersize: 4
  default_style:
    color: [0.55, 0.55, 0.9]
    markersize: 0
    linewidth: 2
    linestyle: "solid"


init: |
  # Load libraries that will be used throughout the configuration file.
  import re
  import glob
  import numpy as np
  import os.path as op
  import neuropythy as ny
  from struct import unpack
  from matplotlib.colors import LinearSegmentedColormap

  # Define directories
  dataset  = "nsd"
  data_dir = op.join("/home", "jovyan", "datasets", dataset)

  # define flatmap kwargs
  FLATMAP_KWARGS = {
    "mask"      : ( "parcellation", 43 ), 
    "map_right" : "right",
    "radius"    : np.pi / 2
  }

  # load fsaverage as a subject object
  fsa = ny.freesurfer_subject("fsaverage")

  # prepare fsaverage flatmap
  fsa_flatmaps = {} # initialize
  fsa_flatmaps["lh"] = fsa.hemis["lh"].mask_flatmap(**FLATMAP_KWARGS)
  fsa_flatmaps["rh"] = fsa.hemis["rh"].mask_flatmap(**FLATMAP_KWARGS)

  # define a custom colormap for isoeccentricity figures
  edge_cmap = LinearSegmentedColormap.from_list(
    name = "edge", 
    colors = [
      (0, (0, 1, 1)),    # negative values begin at cyan
      (0.49, (0, 0, 0)), # black edge, just before the threshold value
      (0.50, (1, 1, 0)), # yellow edge, at the threshold value
      (0.51, (1, 1, 1)), # white edge, just after the threshold value
      (1, (1, 0, 0))     # positive values go towards red
    ]
  )

  
targets:
  # The "Participant" is a choice for the user. It will appear as a dropdown 
  # menu with these two options in the annotation tool.
  Participant:
    - subj01
    - subj02
    - subj03
    - subj04
    - subj05
    - subj06
    - subj07
    - subj08

  # The "Hemisphere" is a choice for the user; as a list of two options, it will
  # appear as a dropdown menu with these two options in the annotation tool.
  Hemisphere:
    - Left Hemisphere
    - Right Hemisphere

  # create subject flatmap.
  flatmap: |
    # get dropdown selections from above choices.
    participant = target["Participant"] # string
    hemi        = target["Hemisphere"]  # string

    # format dropdown items
    fs_hemi = f"{hemi[0].lower()}h"

    # define participant directory
    participant_dir = op.join(data_dir, participant)

    # find all participant property files
    prop_files = glob.glob(op.join(participant_dir, f"{fs_hemi}.2d.*"))

    # read in all subject properties
    props = {} # initialize
    for fname in prop_files: # for each property file
      prop_name = fname.split(".")[-1]
      with open(fname, "rb") as f:
        values = f.read() # read property file, float16
        values = unpack("e" * (len(values) // 2), values)
      props[prop_name] = values

    # copy fsaverage flatmap 
    participant_flatmap = fsa_flatmaps[fs_hemi].copy()

    # attatch and return properties to fsaverage flatmap
    return participant_flatmap.with_prop(props)



annotations:
  # Face Areas (variable)
  Face Areas:
    type: boundary
    variable: true
    variable_options: [ "OFA", "FFA-1", "FFA-2", "mTL-faces", "aTL-faces" ]
    figure_grid: 
     - [ "faces", "curvature" ]
     - [ "angle", "eccen" ]
  # Body Areas (variable)
  Body Areas:
    type: boundary
    variable: true
    variable_options: [ "EBA", "FBA-1", "FBA-2", "mTL-bodies" ]
    figure_grid: 
     - [ "bodies", "curvature" ]
     - [ "angle", "eccen" ]
  # Place Areas (variable)
  Place Areas:
    type: boundary
    variable: true
    variable_options: [ "OPA", "PPA", "RSC" ]
    figure_grid: 
     - [ "places", "curvature" ]
     - [ "angle", "eccen" ]
  # Word Areas (variable)
  Word Areas:
    type: boundary
    variable: true
    variable_options: [ "OWFA", "VWFA-1", "VWFA-2", "mfs-words", "mTL-words" ]
    figure_grid: 
     - [ "words", "curvature" ]
     - [ "angle", "eccen" ]


figures:
  _: |
    ny.cortex_plot(
      mesh  = target["flatmap"], 
      color = key,
      cmap  = "temperature_dark", 
      vmin  = -8,
      vmax  = 8, 
      axes  = axes
    )
  angle: |
    # prepare (formatted) target information for figure code below
    hemisphere = target["Hemisphere"]  # string
    fs_hemi    = f"{hemisphere[0].lower()}h"

    # prepare colormap name and values for figure
    colormap_name   = f"polar_angle_{fs_hemi}"
    colormap_values = target["flatmap"].properties["angle"]

    ny.cortex_plot(
      mesh  = target["flatmap"], 
      color = { colormap_name: colormap_values }, 
      axes  = axes
    )
  eccen: |
    ny.cortex_plot(
      mesh  = target["flatmap"], 
      color = { "eccentricity": target["flatmap"].properties["eccen"] }, 
      axes = axes
    )
  curvature: |
    ny.cortex_plot(mesh = target["flatmap"], axes = axes)
  term: |
    # figure aesthetics and limits
    xy = target["flatmap"].coordinates
    (xmin, ymin) = np.min(xy, axis = 1)
    (xmax, ymax) = np.max(xy, axis = 1)
    axes.set_xlim((xmin, xmax))
    axes.set_ylim((ymin, ymax))